version: "3.8"
services:
  #tftp-nfs-dhcp-server:
  #  build:
  #    context: .
  #  container_name: tftp-dhcp-server
  #  privileged: true
  #  ports:
  #   - "67:67/udp" # DHCP-Server-Port
  #   - "69:69/udp" # TFTP-Server-Port
  # volumes:
  #   - ./tftp/bootfiles:/var/lib/tftpboot
  #   - ./dhcp/dhcpd.conf:/etc/dhcp/dhcpd.conf
  # network_mode: "host"

  nfs-server:
    image: itsthenetwork/nfs-server-alpine:latest
    container_name: nfs-server
    privileged: true
    environment:
      - SHARED_DIRECTORY=/data
    volumes:
      - ./exportfs:/data
    restart: unless-stopped
    network_mode: "host"
