version: "3.8"
services:
  tftp-nfs-dhcp-server:
    build:
      context: .
    container_name: tftp-nfs-dhcp-server
    privileged: true
    ports:
      - "67:67/udp"                 # DHCP-Server-Port
      - "69:69/udp"                 # TFTP-Server-Port
      - "2049:2049"                 # NFS-Server-Port
    volumes:
      - ./tftp/bootfiles:/var/lib/tftpboot
      - ./nfs/rootfs:/exports/rootfs
      - ./dhcp/dhcpd.conf:/etc/dhcp/dhcpd.conf
    network_mode: "host"
